use_frameworks!

platform :ios, '9.0'

target 'TurfSwiftBuffer_Example' do
  pod 'TurfSwiftBuffer', :path => '../'

  target 'TurfSwiftBuffer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
